name: CI - Build, Test, and Push to GHCR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run unit tests
        run: go test -v ./...

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          OWNER_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_ID=ghcr.io/$OWNER_NAME/$REPO_NAME:${{ github.sha }}
          echo "Building and pushing image: $IMAGE_ID"
          docker build -t $IMAGE_ID .
          docker push $IMAGE_ID
            
      - name: Trigger Jenkins Deployment
        run: |
          # Use the corrected, lowercase owner and repo names to build the tag
          OWNER_NAME_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME_LOWER=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          
          # Construct the full image tag that was actually pushed
          FULL_IMAGE_TAG="ghcr.io/$OWNER_NAME_LOWER/$REPO_NAME_LOWER:${{ github.sha }}"
          
          # URL-encode the correct tag and send it to Jenkins
          IMAGE_TAG_URLENCODED=$(echo -n "$FULL_IMAGE_TAG" | jq -sRr @uri)
          curl -X POST ${{ secrets.JENKINS_URL }}/job/deploy-app/buildWithParameters \
            --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} \
            --data-urlencode "IMAGE_TAG=${IMAGE_TAG_URLENCODED}"